### ISSUE TITLE
Improve error handling when an invalid app id is used

### ISSUE THREAD

**Issue by dsmerritt** [bitstadium/HockeySDK-Xamarin#10]
I was experimenting with this SDK at the Xamarin Evolve mini hacks area. https://github.com/xamarin/mini-hacks

The sample code leads to a NullReferenceException when an invalid App Id is used. It is easily fixed by using a valid App Id but the error does not point you in the right direction. Can the error reporting for invalid app ids be improved?

The way it works now the invalid app id is not caught until you try to use the Authenticator object on the SharedHockeyManager.

Ideally, .Configure or .StartManager would throw an exception indicating the app id is invalid.

``` cs
 //Get the shared instance
var manager = BITHockeyManager.SharedHockeyManager;

//Configure it to use our APP_ID
manager.Configure ("<APP_ID>");

//Start the manager
manager.StartManager ();

//Authenticate (there are other authentication options)
manager.Authenticator.AuthenticateInstallation ();    
// ^ NRE here if APP_ID is invalid
```

**Comment by lumaxis** [comment]
Thanks for the pointer @dsmerritt! We will definitely look into improving this in the future.
If you want to help speed this along, feel free to open a Pull Request - we highly appreciate any help from the community! 😊
