### ISSUE TITLE
Manual Feedback sending stopped working

### ISSUE THREAD

**Issue by dgrabar** [bitstadium/HockeySDK-Xamarin#100]
Since few days, programmatic feedback cannot be sent from Android. It worked for months, and our code has not changed in the meantime.

Error: "Message couldn't be posted. Please check your input values and your connection, then try again."

**Comment by TroubleMakerBen** [comment]
Hey @dgrabar,
I see that you closed this issue. Have you solved the issue? Let me know if you need anything from me.

Best,
Benjamin
