### ISSUE TITLE
ShowFeedbackActivity Java File and Uri

### ISSUE THREAD

**Issue by emmanuele-villa** [bitstadium/HockeySDK-Xamarin#104]
I'm trying to pass a file uri to the ShowFeedbackActivity method, but it needs an Android.Net.Uri which needs to be created from a Java.IO.File, but the xamarin android sdk's method Context.OpenFileOutput(..) returns a System.IO.File

In my example, I'm trying to attach a log file to the FeedbackActivity, so how can I create the local file, generate its uri and pass it to the activity if the two api types are different? Am I doing it wrong or there is no way at the moment?

If there is another easier method to pass the log (which I have in a form of a big string) I can change to that way

Thanks

**Comment by emmanuele-villa** [comment]
Update:
I tried another approach by creating the file with System.IO.File.WriteAllText(path, string) and then create the uri with Java.IO.Uri.Parse(path).
I can see the file in the feedback activity: https://www.dropbox.com/s/6tiog33v5p11bcg/feedback.jpeg?dl=0
but when I tap send I get a FileNotFoundException:
https://www.dropbox.com/s/4wffui37uqlusck/Schermata%202017-12-08%20alle%2015.27.00.png?dl=0

**Comment by MatkovIvan** [comment]
Regarding `MalformedURLException`:
You probably missed call `FeedbackManager.Register`. Please recheck all steps from [integration manual](https://support.hockeyapp.net/kb/client-integration-cross-platform/how-to-integrate-hockeyapp-with-xamarin#2-7-add-in-app-feedback)

**Comment by MatkovIvan** [comment]
JFYI I added readable error if FeedbackManager register call is missed https://github.com/bitstadium/HockeySDK-Android/pull/341

**Comment by emmanuele-villa** [comment]
Thanks! Indeed I missed the register call.. my fault :(
Thanks for the user-friendly error 👍
