### ISSUE TITLE
5.1.x crashes on manager.StartManager() in iOS app extension

### ISSUE THREAD

**Issue by kspearrin** [bitstadium/HockeySDK-Xamarin#111]
We recently updated the HockeyApp SDK lib in our project from 5.0.0 to 5.1.1 and noticed that our iOS action app extension no longer works after doing so.

Debugging our app extension we can see that the app crashes on the `StartManager()` line as shown here:

    var crashManagerDelegate = new HockeyAppCrashManagerDelegate(appIdService, Resolver.Resolve<IAuthService>());
    var manager = HockeyApp.iOS.BITHockeyManager.SharedHockeyManager;
    manager.Configure("OURUUID", crashManagerDelegate);
    manager.CrashManager.CrashManagerStatus = HockeyApp.iOS.BITCrashManagerStatus.AutoSend;
    manager.UserId = appIdService.AppId;
    manager.StartManager();

Source:

https://github.com/bitwarden/mobile/blob/e90501a986a4f23c922f87c1a5ae94c77bb556bc/src/iOS.Extension/LoadingViewController.cs#L58

Unfortunately no exception seems to be thrown. I even wrapped `manager.StartManager()` in a try/catch but was not able to catch the error. The extension just hard fails. I was able to get this from the XCode device logs, however:

https://gist.github.com/kspearrin/158d4dd37ad9c7f6b8472fe6ed9d286c

I think the crash is logged as a `SIGNAL` crash around line 392 of that gist.

Downgrading our project back to 5.0.0 causes the problem to go away and the app extension works as expected. No problems were observed with the main app using 5.1.1 though ([here](https://github.com/bitwarden/mobile/blob/master/src/iOS/AppDelegate.cs#L48)), which is quite odd.

**Comment by TroubleMakerBen** [comment]
Hey @kspearrin,

thx for letting is know about this. We'll look into the issue and be in touch as soon as we have any news about this.
My apologies for causing any inconveniences.

Best,
Benjamin
