### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1 - java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by UnDiogO** [bitstadium/HockeySDK-Xamarin#117]
Getting the error using version 5.1.0

05-09 16:41:13.914: E/AndroidRuntime(31114): FATAL EXCEPTION: AsyncTask #1
05-09 16:41:13.914: E/AndroidRuntime(31114): Process: "PackageName", PID: 31114
05-09 16:41:13.914: E/AndroidRuntime(31114): java.lang.RuntimeException: An error occurred while executing doInBackground()
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.lang.Thread.run(Thread.java:818)
05-09 16:41:13.914: E/AndroidRuntime(31114): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at net.hockeyapp.android.Constants$2.doInBackground(Constants.java:197)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at net.hockeyapp.android.Constants$2.doInBackground(Constants.java:194)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 16:41:13.914: E/AndroidRuntime(31114): 	... 3 more

**Comment by MatkovIvan** [comment]
Hi @UnDiogO 

Thanks for getting in touch.
It looks like you initialized HockeyApp with null context.

PS The error definitely should be more clear.

Best,
Ivan
