### ISSUE TITLE
HockeyApp support for Xamarin.Mac or Xamarin.Forms Mac

### ISSUE THREAD

**Issue by E-Mani** [bitstadium/HockeySDK-Xamarin#118]
Hi Team, 

I have tried HockeyApp in **Xamarin.Mac or Xamarin.Forms Mac**, but i can't integrate into my project. Does it support **Xamarin.Mac or Xamarin.Forms Mac** ?

Thanks,
Mannan E

**Comment by elamalani** [comment]
@E-Mannan Thanks for using HockeyApp. We don't support Xamarin Mac platform in this product. [App Center](https://appcenter.ms) is the next generation of HockeyApp and our team is working on adding new features there. 

Unfortunately, we don't plan to support Xamarin Mac in HockeyApp.
