### ISSUE TITLE
Register CrashManager with CrashManagerListener doesn't work

### ISSUE THREAD

**Issue by chrwend** [bitstadium/HockeySDK-Xamarin#12]
[A customer](https://support.hockeyapp.net/discussions/problems/56323-re-integrating-hockeyapp-sdk-in-xamarinandroid-crash-reporting?mail_type=queue) tried to register the `CrashManager` with a `CrashManagerListener` instance in order to add user info such as contact, user ID, and email to the crash report. However, this doesn't seem to work. The crash reports are sent without containing any metadata.

My guess is that setting the listener is not properly supported at the moment.

**Comment by SplashLanding** [comment]
Is it possible to create a sample using this, please?
