### ISSUE TITLE
Thread.nativeCreate java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by UnDiogO** [bitstadium/HockeySDK-Xamarin#120]
Getting the error using version 5.1.0

Xamarin caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
java.lang.Thread.nativeCreate(Native Method)
java.lang.Thread.start()Thread.java:1063
java.util.concurrent.ThreadPoolExecutor.addWorker()ThreadPoolExecutor.java:921
java.util.concurrent.ThreadPoolExecutor.execute()ThreadPoolExecutor.java:1328
android.os.AsyncTask.executeOnExecutor()AsyncTask.java:607
net.hockeyapp.android.utils.AsyncTaskUtils.execute()AsyncTaskUtils.java:21
net.hockeyapp.android.Constants.loadIdentifiers()Constants.java:194
net.hockeyapp.android.Constants.loadFromContext()Constants.java:122
net.hockeyapp.android.UpdateManager.register()UpdateManager.java:126
net.hockeyapp.android.UpdateManager.register()UpdateManager.java:87
md52f9617da6bfda7fb720bf61d182a6069.MainActivity.n_onCreate(Native Method)
md52f9617da6bfda7fb720bf61d182a6069.MainActivity.onCreate()MainActivity.java:54
android.app.Activity.performCreate()Activity.java:6904
android.app.Instrumentation.callActivityOnCreate()Instrumentation.java:1136
android.app.ActivityThread.performLaunchActivity()ActivityThread.java:3266
android.app.ActivityThread.handleLaunchActivity()ActivityThread.java:3415
android.app.ActivityThread.access$1100()ActivityThread.java:229
android.app.ActivityThread$H.handleMessage()ActivityThread.java:1821
android.os.Handler.dispatchMessage()Handler.java:102
android.os.Looper.loop()Looper.java:148
android.app.ActivityThread.main()ActivityThread.java:7406
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1230
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1120

**Comment by MatkovIvan** [comment]
Hi @UnDiogO,

Thanks for getting in touch!
It looks like this isn't directly related to HockeyApp SDK. Please check if you properly closing input/output stream or buffers.
You can also increase the size of the Java heap. See [this document](https://developer.android.com/guide/topics/manifest/application-element.html#largeHeap) for more information.

Best,
Ivan

**Comment by aleksandrsmyk** [comment]
I have the same issue. I updated from 4.1.2 to 5.1.1 and a lot of these crashes are in the app now. Please, fix it

**Comment by MatkovIvan** [comment]
@aleksandrsmyk Do you have any additional info that may be useful? What OS version, device model? Have you changed anything else in addition to the HockeyApp update? How much memory does your app typically use? Does this happen when the application starts or under a certain action?

**Comment by MatkovIvan** [comment]
We haven't heard from you for a while. I'll close this issue for now but feel free to reach out to us in case of any questions.
