### ISSUE TITLE
HockeySDK Feedback Only uGet

### ISSUE THREAD

**Issue by christianhelle** [bitstadium/HockeySDK-Xamarin#128]
I'm working on a Xamarin based project that is currently using AppCenter but we suddenly are required to support in-app feedback. I used this before from HockeyApp and that worked fine but AFAIK I can't use HockeyApp and AppCenter side by side in iOS. I noticed that there is a FeedbackOnly nuget package in the release section but I can't seem it on nuget.org

Are there plans to make the feedback only nuget package public?

**Comment by elamalani** [comment]
@christianhelle Unfortunately, we don't plan to release HockeyApp Xamarin SDK with Feedback only NuGet. I'll keep this issue open for now and we will keep you posted if our plan changes in the future. Thanks for using App Center.

**Comment by christianhelle** [comment]
Thanks for the response. I found a way around it by publishing the nupkg you provide to a private nuget feed. It works pretty fine but I would prefer of course that this would be hosted publicly on nuget.org instead of having them together with our internal company libraries
