### ISSUE TITLE
HockeyApp SDK 5.1.1 and AppCenter

### ISSUE THREAD

**Issue by AndrewProteo** [bitstadium/HockeySDK-Xamarin#132]
Hi What are the plans for updating the Xamarin version for the HockeyApp-SDK 5.1.1 changes currently happening around AppCenter, we are getting intermittent problems with updating our restricted distribution groups, and i was told to update to the latest HockeyApp SDK.

**Comment by guperrot** [comment]
Can you elaborate on what intermittent problems are you facing? Please include as many details as possible.

**Comment by ElektrojungeMS** [comment]
One more comment from my side: The current version of the HockeySDK for Xamarin is 5.1.2, did you upgrade to it already?

**Comment by jwallra** [comment]
I'm going to close this as it's stale and we still need more details.  If you are still facing the issue, feel free to reopen and include more info.
