### ISSUE TITLE
Native Linker failures in Xamarin.iOS

### ISSUE THREAD

**Issue by JAgostoni** [bitstadium/HockeySDK-Xamarin#30]
Maybe I missed this in the docs somewhere but when I added the SDK to my (previously created) iOS Xamarin.Forms add I was getting linker failures on some standard library bits.

I had to add the following as additional mtouch arguments:
-cxx -gcc_flags "-lc++"

Am I missing something else?  Did I forget a step somewhere?

**Comment by lumaxis** [comment]
Hey @JAgostoni! This is actually a known issue which we are currently investigating. It does to only appear if you set your project's settings to "Link All Assemblies" though.

**Comment by JAgostoni** [comment]
Thanks for the reply. I actually get the error no matter which linker setting I used. I'll replicate the error today and post a full error message to make sure.

**Comment by JAgostoni** [comment]
If I run a build any of the linker settings (Don't Link, Link Framework SDKs Only, or Link All) and do not use the additional touch arguments above I get the following errors:

```
MTOUCH: error MT5210: Native linking failed, undefined symbol: std::__1::__vector_base_common<true>::__throw_length_error() const. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: std::rethrow_exception(std::exception_ptr). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: std::current_exception(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: std::exception_ptr::exception_ptr(std::exception_ptr const&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: std::exception_ptr::~exception_ptr(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5202: Native linking failed. Please review the build log.
```

Regardless of linker settings, if I add the arguments back in I get a successful build.

Interestingly enough, if I create a brand new Xamarin Forms project I do not get the same problem.  I wonder if it is any different if I create the project using Visual Studio (vs. using Xamarin Studio like I just did).  I'll try that when I get a chance.
