### ISSUE TITLE
Logging events doesn't seem to work at all

### ISSUE THREAD

**Issue by Korayem** [bitstadium/HockeySDK-Xamarin#35]
I have following configured in my app yet nothing is showing in the backend

`Droid/MainActivity.cs`

	MetricsManager.Register(this, Application, HOCKEYAPP_APPID);
	MetricsManager.EnableUserMetrics();

Then I log events normally in Android code:
	HockeyApp.Android.Metrics.MetricsManager.TrackEvent(eventName);

**Comment by TroubleMakerBen** [comment]
Hi Korayem,

Are you using 4.1.0-beta.3 of the SDK?

Best,
Benjamin

**Comment by Korayem** [comment]
Confirmed, yes 4.1.0-beta3

**Comment by TroubleMakerBen** [comment]
Hey Korayem,

Are you a member of our preseason program? Without being a member, you won't be able to see custom events on HockeyApp.

If you're not a member, please open a ticket in our [support system](https://support.hockeyapp.net).

Best,
Benjamin

**Comment by Korayem** [comment]
The app is shared between two accounts, one that's member of `Preseason` while the other isn't.

Is that why I am getting duplicate records of same version ever since I upgraded to `beta3`?
![image](https://cloud.githubusercontent.com/assets/198332/16481314/e20066e0-3eaa-11e6-9168-b1b7c669f817.png)

v18 First one shows `unknown SDK`:
![image](https://cloud.githubusercontent.com/assets/198332/16481360/247f806e-3eab-11e6-896f-bc347b0f9f86.png)

While v18 Second one shows `beta2`:
![image](https://cloud.githubusercontent.com/assets/198332/16481385/47785d84-3eab-11e6-9e8b-54138cf1c379.png)

Though I updated the nuget package from `beta2` to `beta3`:
![image](https://cloud.githubusercontent.com/assets/198332/16481408/70cbfa7e-3eab-11e6-8a29-420ceef9388f.png)

**Comment by ranterle** [comment]
Custom Events is now available for every HockeyApp customer, no Preseason required anymore. Please do let us know here or in [support](https://support.hockeyapp.net/) if there still is a problem. We also will be releasing the stable version of 4.1 soon, stay tuned.
