### ISSUE TITLE
feedback closed event

### ISSUE THREAD

**Issue by amccorma** [bitstadium/HockeySDK-Xamarin#39]
Not a bug a suggestion.  Extend the feedback listener to know when the feedback window has closed.

**Comment by ranterle** [comment]
This will be the diligence of the native SDKs before the Xamarin SDK can report on this - which platforms are you asking for?

**Comment by amccorma** [comment]
Android and iOS.

**Comment by amccorma** [comment]
I get the current view visible and check if the feedback activity or view.  easiest way be to set a variable whether is open or closed.

**Comment by ranterle** [comment]
I've added this to our backlog - feel free to open a PR.

**Comment by ranterle** [comment]
This will have to be supported by both underlying platform SDKs and then the Xamarin SDK can follow. At the moment we can't give an ETA when this will be supported.
