### ISSUE TITLE
Publish as a nuget package

### ISSUE THREAD

**Issue by MisterJimson** [bitstadium/HockeySDK-Xamarin#40]
Hello,

I see that this library is available as xamarin components [here for iOS](https://components.xamarin.com/view/hockeyappios) and [here for Android](https://components.xamarin.com/view/hockeyappandroid).

Is it possible to also have them as nuget packages (or ideally a single package) on [nuget.org](https://www.nuget.org/)?

Xamarin components are quite inferior to nuget packages.

Thanks

**Comment by MisterJimson** [comment]
Nvm its right here https://www.nuget.org/packages/HockeySDK.Xamarin/.

The website only links to the components here https://hockeyapp.net/releases/

**Comment by TroubleMakerBen** [comment]
@MisterJimson 👌🏻 thx for bringing this to our attention. I'll update the releases page on our website.
