### ISSUE TITLE
Send crash report in iOS

### ISSUE THREAD

**Issue by DiegoV71** [bitstadium/HockeySDK-Xamarin#41]
Hi, I include this component in iOS project and code in appdelegate
```C#
var manager = BITHockeyManager.SharedHockeyManager;
manager.Configure("*MyAppID*");
manager.CrashManager.CrashManagerStatus = BITCrashManagerStatus.AutoSend;
manager.StartManager();
```
but reports about my `throw new Exception("message")` not send to service; help me please;

**Comment by DiegoV71** [comment]
On android this component is working;

**Comment by TroubleMakerBen** [comment]
Hi @DiegoV71,

I just saw your comment here after I replied to your issue in [our iOS SDK Repo](https://github.com/bitstadium/HockeySDK-iOS/issues/314). Which SDK are you seeing this issue with and which version are you using?

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Closing this as you've submitted a ticket to our support system.
