### ISSUE TITLE
35mb library for iOS seems too big

### ISSUE THREAD

**Issue by nevalenny** [bitstadium/HockeySDK-Xamarin#42]
For Xamarin.Forms app built in Release mode the library takes almost half the app size. Doesn't seem too good library for mobile development.

![hockeysdk iosbindings_35mb](https://cloud.githubusercontent.com/assets/8243681/18122956/6a543860-6f74-11e6-8f9c-4a833a939f2c.png)

**Comment by nevalenny** [comment]
And from top 3 sized libraries two (means PLCrashReported too) belongs to HockeySDK

**Comment by anlinde** [comment]
The symbol size has nothing to do with your app size and are not part of the app that you submit to Apple. Why are the sizes of the symbols that are needed for crash symbolication a concern?

**Comment by nevalenny** [comment]
@anlinde 
I mean the size of HockeySDK.iOSBindings.dll and PLCrashReporterUnifiedBinding.dll that add to my TrackerMobile.iOS.app file.

**Comment by Cheesebaron** [comment]
What is the size after linking?

**Comment by nevalenny** [comment]
Looks like i overwatched the package contents, the library size inside the app package is less then 10kb.
