### ISSUE TITLE
HockeyApp documention is wrong, says to use non-existant namespace

### ISSUE THREAD

**Issue by bholmes** [bitstadium/HockeySDK-Xamarin#43]
Original bug from [43359](https://bugzilla.xamarin.com/show_bug.cgi?id=43359)

Install the HockeyApp for iOS component 4.1.0.2.  The documentation says to use "using HockeySDK.iOS;".  There is no such thing.

component/ios/GettingStarted.md

Should be HockeyApp.iOS

https://github.com/bitstadium/HockeySDK-Xamarin/blob/88cd5b16e53d734be9499dc9ce846e3ca4adfb82/source/HockeySDK.iOSBindings/ApiDefinition.cs#L7

**Comment by ranterle** [comment]
Thanks for reporting this, will fix it in the next version of the component description.
