### ISSUE TITLE
Authenticator is null in example code

### ISSUE THREAD

**Issue by follesoe** [bitstadium/HockeySDK-Xamarin#44]
The ``manager.Authenticator`` is NULL, causing a ``NullReferenceException`` on start-up. Is there something missing from the example in the readme file?

```csharp
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions) {
   var manager = BITHockeyManager.SharedHockeyManager;
   manager.Configure("Your_App_Id");
   manager.StartManager();
   manager.Authenticator.AuthenticateInstallation(); // This line is obsolete in crash only builds
}
```

**Comment by lumaxis** [comment]
You of course need to replace `"Your_App_Id"` with a real App ID :)

**Comment by follesoe** [comment]
Sure - but is that the cause of the Authenticator being null? I have replaced the app id with what (as far as I can tell) is the correct App Id.

**Comment by follesoe** [comment]
Setting the correct App ID solved the problem. So I'll close this issue, but would at the same time suggest a more descriptive error message.

**Comment by lumaxis** [comment]
Yes, this is on our radar 👍 The current error handling process is not very helpful or descriptive.
