### ISSUE TITLE
Droid: MetricsManager.Register(this, Application, "$Your_App_Id");

### ISSUE THREAD

**Issue by markmadlangbayan** [bitstadium/HockeySDK-Xamarin#51]
I just upgraded to 4.1.0, it's saying that this is obsolete.  What's the best way to enable User Metrics?

-Mark

**Comment by TroubleMakerBen** [comment]
Hey @markmadlangbayan,
thx for getting in touch I just found that the readme here uses a deprecated API. I'll fix that in a bit.

Now, about setting up Metrics, you should use `MetricsManager.Register(this, "$YOUR_APP_ID);`

**Comment by markmadlangbayan** [comment]
No problem.  Thanks!Date: Fri, 16 Sep 2016 10:50:36 -0700
