### ISSUE TITLE
Reporting to wrong version

### ISSUE THREAD

**Issue by amccorma** [bitstadium/HockeySDK-Xamarin#53]
My Info.plist file says version: 196729, but crash reports are getting reported to version 196727.

**Comment by TroubleMakerBen** [comment]
Hi @amccorma 
This is something that happens often "accidentally" as the version that was uploaded to HockeyApp and is used by testers has a different version than the one on the dev machine. It has happened to me myself.
If you're 100% sure that the builds are correct and the crashes end up in the wrong version, please contact us through [support](https://support.hockeyapp.net) so we can have a closer look.

Benny

**Comment by amccorma** [comment]
It happens every day, every hour with every new crash.  I have emailed support and nothing for days.

**Comment by anlinde** [comment]
Hi @amccorma, you got a response in support on September 26th 8 minutes after you mailed us with a request for further information. Please check your emails (spam folder too) or try this link: https://support.hockeyapp.net/discussions/problems/63112-wrong-version-for-crashes
