### ISSUE TITLE
crash on iPhone 3GS

### ISSUE THREAD

**Issue by thomiel** [bitstadium/HockeySDK-Xamarin#54]
If I only put the line "var manager = BITHockeyManager.SharedHockeyManager;" in AppDelegate.FinishedLaunching the app continues to shut down after a few seconds each time I start it. If I comment it out, the app starts without problems.

**Comment by Cheesebaron** [comment]
A good idea is to provide a Stack Trace if you have one.

**Comment by thomiel** [comment]
Sorry, I don't have one. There is no exception, nothing I can pin it to, the app just shuts down.

**Comment by TroubleMakerBen** [comment]
@thomiel Which iOS version (iOS 6?) and which SDK version are you using?

**Comment by thomiel** [comment]
SDK: 9.3, iOS 6.1.6

**Comment by TroubleMakerBen** [comment]
Hi @thomiel,
and you are using HockeySDK-Xamarin 4.1.0?

I'll try and look into this next week.

**Comment by thomiel** [comment]
yes, 4.1.0

**Comment by Spierki** [comment]
+1

**Comment by thomiel** [comment]
@Spierki Florian, what kind of build host do you use?

**Comment by Spierki** [comment]
@thomiel I build my app with Visual Studio and my XCode version on my mac is the latest one (xcode 8)

**Comment by thomiel** [comment]
@Spierki I tried moving from XCode 7.3 to XCode 8, which seemd to have aggrevated the problem. I wonder if this could have to do with my old Mac only having 2GB main memory. Though in system monitor the memory utilization looks fine...

**Comment by thomiel** [comment]
This might be a problem of Xamarin. Maybe adding HockeyApp SDK just was the last straw. I filed a bug report here: https://bugzilla.xamarin.com/show_bug.cgi?id=45052

**Comment by ranterle** [comment]
I'm closing this for now as it looks like a issue with the build host at hand. Please reopen if there is any trouble introduced by HockeyApp.
