### ISSUE TITLE
Strange problem with TabbedPage

### ISSUE THREAD

**Issue by Spierki** [bitstadium/HockeySDK-Xamarin#55]
Hey,
I have a strange problem when I used a TabbedPage with two childs. 

The application is lauching and closing directly with no error message . 

```c#
   class HomePage : TabbedPage
    {
        public HomePage()
        {

            var cardsPages = new NavigationPage(new CardsPageView());
            cardsPages.Title = "Cartes";
         var offerPages = new NavigationPage(new SettingsPageView());
         offerPages.Title = "Promo";

         Children.Add(cardsPages);
         Children.Add(offerPages);
        }
    }
```

I tried my two pages alone (one time with the child cardsPage and the other with the child offerPages), and it seems to be working. Did you ever heard about a problem like that ?

**Comment by Cheesebaron** [comment]
This is not a problem if you remove HockeyApp?

**Comment by Spierki** [comment]
@Cheesebaron I tried and yes, it's working perfectly if I remove the line 

> CrashManager.Register(this, "xxxxx");

**Comment by Spierki** [comment]
@Cheesebaron Downgrading to the last stable version of Xamarin Forms (2.3.2.127) solved the problem

**Comment by TroubleMakerBen** [comment]
@Cheesebaron @Spierki Thanks a lot for letting us know!
