### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by kzisme** [bitstadium/HockeySDK-Xamarin#60]
Both of the documentation links seem to be broken for iOS and Android. 

Received a "Page Not Found" - Have the locations for the docs moved elsewhere I took a look around and didn't notice them anywhere else on the site.  I can update the links if need-be.

![image](https://cloud.githubusercontent.com/assets/3493562/19005835/b4693e14-872a-11e6-8f21-66b367c5417a.png)

**Comment by ranterle** [comment]
Hi @kzisme, sorry for the delay. Which links do you mean exactly? Links here on the repository or somewhere else?

**Comment by kzisme** [comment]
@ranterle Sorry for the delayed reply - links here within the repository(readme.md).  

[Documentation](https://github.com/bitstadium/HockeySDK-Xamarin#documentation) leads to iOS and Android - which both lead to the above screenshot "Page Not Found".  

Sorry for not initially including a link. 

Are those meant to be broken/moved/updated?

**Comment by ranterle** [comment]
Hi @kzisme - thanks for the follow up and sorry for following up late - the team is very busy right now.
I've fixed the documentation links in the readme.

**Comment by kzisme** [comment]
@ranterle No worries - it's a super minor issue just though I'd bring it up.

Thanks!
