### ISSUE TITLE
Migrating from Xamarin.Insights: Missing Features "Report & Identify"

### ISSUE THREAD

**Issue by gentledepp** [bitstadium/HockeySDK-Xamarin#63]
Hi!

As we understood, Xamarin plans to shut down Xamarin Insights and ask its devs to move to HockeyApp.

Basically, I do not have a problem with that.
The only thing is, that it still is lacking two features which are very important to us:

1) Insights.Report(...) allows us to report exceptions which did NOT cause the App to crash. (But they might still be interesting to us! This cannot be compensated with "Track" as we would loose the stacktrace, etc. etc.)

2) Insights.Identify(...) allows us to add general metadata to a current session.
That way we can better identify problems and/or customers.
And we do NOT have to add that information in each call - it is just added out of the box.

Once those two features are available, I can think of changing the platform, but until then HockeyApp is useless as metrics-provider to us. :-|

Are there any plans to implement those?

**Comment by albertoms** [comment]
Hi, @gentledepp 

I achieved the Identify part implementing the `BITHockeyManagerDelegate`:

```
public class HockeyAppDelegate : BITHockeyManagerDelegate
	{
		public override string UserIdForHockeyManager (BITHockeyManager hockeyManager, BITHockeyBaseManager componentManager)
		{
			return (string.IsNullOrEmpty(Settings.Current.ClientId) ? "Logged out" : Settings.Current.ClientId );
		}

		public override string UserNameForHockeyManager (BITHockeyManager hockeyManager, BITHockeyBaseManager componentManager)
		{
			return Settings.Current.FullName;
		}

		public override string UserEmailForHockeyManager (BITHockeyManager hockeyManager, BITHockeyBaseManager componentManager)
		{
			return Settings.Current.Email;
		}
	}
```

I hope you can find this snippet useful.

**Comment by gentledepp** [comment]
Thank you for this  - however, why on earth do I need a platform-dependant API for this?
This was actually solved beautifully by Xamarin.Insights as you could use the whole api from a PCL project....

Now I got accepted to the brand new "Visual Studio Mobile Center" and we've the same issue there:
No way to identify a user, and no way of reporting any exceptions which did **not** lead to a crash... :-|

**Comment by albertoms** [comment]
I feel you. The bright side of this is that you can learn a bit more about DependencyService implementing this feature if you use Xamarin Forms.

I disabled crash reporting on iOS because the Xamarin component is not updated to the latest version from the iOS SDK. I'm still using Insights to track some errors. I hope they can solve this issues soon before my team decide to move our logs to another crash reporting platform.

**Comment by ranterle** [comment]
Hey @gentledepp & @albertoms - we are working on Mobile Center to include both handled exceptions and additional crash meta data through our new open source SDKs. We are working to get a public roadmap out, please stay tuned. Also, when in Mobile Center, you can use the Intercom feature to contact the team directly who is working on the roadmap. We have heard your requests and greatly appreciate your feedback!

**Comment by gentledepp** [comment]
Awesome - I just used that intercom yesterday to ask about the progress on these features 
Thanks for the heads-up!
