### ISSUE TITLE
Not Working on Xamarin.Forms UWP Projects.

### ISSUE THREAD

**Issue by rdeveen** [bitstadium/HockeySDK-Xamarin#65]
Please, update the solution to also work with Xamarin.Forms UWP Projects.

**Comment by ranterle** [comment]
Hi @rdeveen - currently the Xamarin SDK for HockeyApp is meant for iOS and Android projects only. We will look into supporting UWP solutions with even better support for the whole Xamarin platform in Mobile Center, you can find all about it [here](https://www.visualstudio.com/vs/mobile-center/).

**Comment by No1e** [comment]
Hi @ranterle 
Mobile Center is in preview at the moment and release date is unknown. 
Microsoft do not recommend Mobile Center to be use in productive apps.

So what can we do? Can we expect that you will support UWP in HockeyAPP?

**Comment by TroubleMakerBen** [comment]
Hey @No1e,

We are evaluating this right now. I will let you know as soon as I have news on this.
Apologies for this rather vague answer at this point.
Best,
Benny

**Comment by EricB84** [comment]
Yes,
It would be a good thing if the 3 platforms are supported.

**Comment by TroubleMakerBen** [comment]
Hey folks,

I can't give you any more info about a timeline for HockeyApp right now (I will give you a heads up as soon as I have more info), but the next version of HockeyApp, Mobile Center, will have UWP support soon. Please have a look at our [info page](https://hockeyapp.net/mobile-center/about/) and let me know what you think or in case you have questions.

**Comment by EricB84** [comment]
hello

OK thanks you for your work.

**Comment by No1e** [comment]
I contact Microsoft and got information that Mobile Center shall not be used for productive apps since it is in "Preview". Also, I got information that in the best case it will be released at the end of this year. 

So what shall we suppose to do until then?

**Comment by TroubleMakerBen** [comment]
Hey @No1e,

I feel you. Mobile Center will support UWP very soon but it will have the "don't use in production"-statement attached to it for now. That said, we already have customers who use iOS/Android/Xamarin in production.
I'm sorry that I don't have a better, more satisfying answer for you. I can assure you that we are working very hard and iterating very fast.

Benny

**Comment by brminnick** [comment]
@n01e

Hockeyapp has a separate NuGet package for UWP. 

Here's a sample app that shows how to implement it in a Xamarin.Forms solution:
https://github.com/brminnick/MyWeather.Forms

**Comment by TroubleMakerBen** [comment]
Thank you for pointing this out @brminnick =)

**Comment by helzgate** [comment]
So we should use the following:?

id="HockeySDK.Xamarin" version="4.1.5"
and
"HockeySDK.UWP": "4.1.6"
