### ISSUE TITLE
How to add the add the Custom Information like description, contact with crash log?

### ISSUE THREAD

**Issue by fahadrehman** [bitstadium/HockeySDK-Xamarin#66]

**Comment by fahadrehman** [comment]
![image](https://cloud.githubusercontent.com/assets/7273661/20755539/2d8031c8-b731-11e6-8ce6-c52e3491c06d.png)

Filed Given on website in Crash Log

**Comment by ranterle** [comment]
Hi @fahadrehman 
please follow the following instructions on how to send additional user data with crash reports:
- iOS: https://github.com/bitstadium/HockeySDK-iOS#364-attach-additional-data
- Android: https://github.com/bitstadium/HockeySDK-Android#422-attach-additional-meta-data

**Comment by nosmirck** [comment]
Hi! We are trying the same thing, however, we haven't had any success.

Can you provide some example code?

On a more detailed description of our problem:

- We are trying this in the MainActivity inside the Android Project in Xamarin.
- We've tried creating a new CrashMetaData object "CrashMetaObj"  and did: CrashManager.HandleUserInfo(CrashManagerUserInput.CrashManagerUserInputAlwaysSend, CrashMetaObj, null, null, true); and didn't work (no user information visible on the crash)

All we want is to include in the crash report (as additional metadata or part of the stack trace) the userID that caused the crash in the app and some extra information (a bunch of strings) that are part of the app's logic that we'd like to see somewhere.

Thanks in advance for any help.

**Comment by nosmirck** [comment]
I'm going to answer my own question in case someone else get here.

Using Xamarin.Forms you can set the User's ID, email and add a description like this:

For Android:

First you need this class:
```
public class MyCrashManagerListener : CrashManagerListener
{
    //you can refactor this with proper get/set methods, this was done for testing purposes
    public string _userID;
    public string _description;
    public override string UserID
    {
        get
        {
            return base.UserID + _userID;
        }
    }
    public override string Description
    {
        get
        {
            return base.Description + _description;
        }
    }
    public override bool ShouldAutoUploadCrashes()
    {
        return true;
    }
    //Override as many properties as you want.
}
```

Then on your MainActivity.cs:
```
MyCrashManagerListener ml = new MyCrashManagerListener();
ml._userID = "YOUR_USER_ID";
//do the same for email and other properties as needed
ml._description = "THIS IS A DESCRIPTION";
CrashManager.Register(this, CELPMobileCentralConfiguration.HockeyAppAPIKey, ml);
```

For iOS, you don't need any extra class, just add this to your AppDelegate.cs:
```
var manager = BITHockeyManager.SharedHockeyManager;
manager.Configure("YOU_APP_ID");
manager.UserId = "YOUR_USER_ID";
manager.UserName = "YOUR_USER_NAME";
manager.UserEmail = "YOUR_USER_EMAIL";
//not tested, description can't be set, but a " Insert " might work.
manager.Description.Insert(manager.Description.Length-1, "THIS IS A DESCRIPTION");
manager.Authenticator.AuthenticateInstallation();
manager.CrashManager.CrashManagerStatus = BITCrashManagerStatus.AutoSend;
manager.StartManager(); 
```

With this, you'll get your crash report with that information on the metadata section as you want it.

**Comment by shnaz** [comment]
If you want both the contact info AND the log, then do this:

![image](https://cloud.githubusercontent.com/assets/6933856/21609267/ae6866d4-d1c1-11e6-9d65-a5d0d4af8d8b.png)
