### ISSUE TITLE
Can you put 4.1.1 on Nuget pre-release?

### ISSUE THREAD

**Issue by skela** [bitstadium/HockeySDK-Xamarin#67]
Just wondering if you could be so kind as to put something up from the 4.1.1 release branch on Nuget as a pre-release package. 

I've no need for any crash reporting, I've got the CrashManager disabled, but even then its crashing on both iOS and Android with unhandled exceptions.

Hoping that the fix mentioned here : https://github.com/bitstadium/HockeySDK-Xamarin/issues/14
will sort it out. 👍

**Comment by ranterle** [comment]
Hi @skela yep, we're working on this. Stay tuned for an update next week.
Best,
Mat

**Comment by ranterle** [comment]
Just wanted to let you know, we just released 4.1.1 to Nuget - official release notes will follow.
