### ISSUE TITLE
Metrics Manager configurable synchronize interval

### ISSUE THREAD

**Issue by joseprl89** [bitstadium/HockeySDK-Xamarin#79]
This stems from [the same issue on the HockeySDK-Android repo](https://github.com/bitstadium/HockeySDK-Android/issues/228) I already raised.

Gist of it, the HockeySDK is not doing an efficient use of the network and there's no way for consumers to tweak so as to better suit our needs.

**Comment by joseprl89** [comment]
The iOS SDK seems to have the same issue:

https://github.com/bitstadium/HockeySDK-iOS/issues/410

**Comment by TroubleMakerBen** [comment]
Closing this as opening 3 issues makes discussion very hard. Let's use [the Android one](https://github.com/bitstadium/HockeySDK-Android/issues/228) for discussion.
