### ISSUE TITLE
Exception setting up the HockeySDK

### ISSUE THREAD

**Issue by czuvich** [bitstadium/HockeySDK-Xamarin#82]
I am getting the following exception on iOS 10.3 and Xamarin Forms 2.3.4.

[HockeySDK] -[BITCrashManager startManagerInSdkEnvironment:]_block_invoke/1265 [HockeySDK] ERROR: Exception handler could not be set. Make sure there is no other exception handler set up!

I have the following code in the AppDelegate OnFinishedLaunching.  Am I missing something? 

var manager = HockeyApp.iOS.BITHockeyManager.SharedHockeyManager;
			manager.Configure(Data.SettingsAccess.Default.AccessSettings.HockeyAppId);
			manager.DisableMetricsManager = true;
			manager.CrashManager.CrashManagerStatus = HockeyApp.iOS.BITCrashManagerStatus.AutoSend;

			manager.StartManager();

**Comment by TroubleMakerBen** [comment]
Hey @czuvich,

Thanks for getting in touch and apologies for the confusing error message.
This is actually expected in a Xamarin environment as Xamarin registers it's own exception handler. That said, this does not mean that Crash Reporting is not working. It will be working as expected.

That said, I've created a task to make sure we add a better log/error message to make sure we are not confusing anyone!

Let me know if you have any other questions and thank you for using HockeyApp.

Benny

**Comment by TroubleMakerBen** [comment]
This will be part of 4.1.5. Yesterday's release (4.1.4) didn't contain an updated native SDK.

**Comment by TroubleMakerBen** [comment]
This was fixed in 4.1.5
