### ISSUE TITLE
Strong name signing for HockeySDK.AndroidBindings

### ISSUE THREAD

**Issue by callanh** [bitstadium/HockeySDK-Xamarin#83]
Hi!

Can you please sign your assemblies in the next update to the nuget packages?

    CSC : warning CS8002: Referenced assembly 'HockeySDK.AndroidBindings, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

We use strong name signing for our projects and it is a bit of a cascading requirement.  In the meantime, I will use the strong name signer tool (https://brutaldev.com/post/net-assembly-strong-name-signer) to workaround the issue.

Thanks
Callan.

**Comment by Cheesebaron** [comment]
Please don't waste your time on strong name signing things.

**Comment by callanh** [comment]
As you might know, if you have the requirement for one strong named assembly, all referenced assemblies must also be strong named.

My dependencies are a bit complicated but I'll try to explain. The high level is I have an application implemented on four platforms (WPF/UWP/Android/iOS).

The WPF project is strong named (so it can be installed in the GAC) and it references a shared PCL (so the PCL must be strong-named).

My Android project also references this shared PCL. The Android library is a 'friend' (InternalsVisibleTo) to the shared PCL (so this means it must also be strongly named or it can't be a 'friend').

**Comment by TroubleMakerBen** [comment]
Hi @callanh,

I've discussed this with the other team members and we won't use strong name signing in our SDK so you need to strong name sign the SDK yourself.
Most people think of strong name signing as a security enhancement which it isn't, as it's easily broken. 
We are aware that it's needed in some cases too, particularly if the assembly is going to be in the Gac, but we don't see the need to cover this edge case. We will reconsider this if we hear more people speaking out with that issue but, frankly, you are the first one do mention that.

Best,
Benjamin
