### ISSUE TITLE
Difference observed between Mobile Center and HockeyApp symbolication

### ISSUE THREAD

**Issue by tylersouthard** [bitstadium/HockeySDK-Xamarin#84]
I recently started incorporating HockeySDK.Xamarin 4.1.3 into our Xamarin.iOS app. The crash logs appear to be missing the C# stack trace, and I only see the native one. I tried out Mobile Center, and the crash logs were properly symbolicated and contained the C# stack. Screenshots of the same crash observed on HockeyApp and Mobile Center are attached.

Mentioned this briefly to @anlinde through Mobile Center chat, but wanted to make sure it got documented here.

![hockeyapp](https://cloud.githubusercontent.com/assets/28648423/25994207/0422530e-36db-11e7-9e8c-dde735092ba1.png)
![mobilecenter](https://cloud.githubusercontent.com/assets/28648423/25994227/185b2f30-36db-11e7-9342-9a12ce6a5c1a.png)

**Comment by TroubleMakerBen** [comment]
Hey Tyler,
thx for getting in touch.
I got the support ticket by Andreas and will look into that. =)
I'll update the issue here as well.

🖖
Benny

**Comment by TroubleMakerBen** [comment]
Hi @tylersouthard,

What you are seeing is a regression that was introduced in HockeySDK-Xamarin 4.1.3 =(.
I just released 4.1.4 that fixes the regression and provides complete stacktraces again.

Apologies for any inconvenience this has caused you. 

Best,
Benny
