### ISSUE TITLE
Support macOS with Xamarin.Forms 2.3.5 on Xamarin.Mac V2.0

### ISSUE THREAD

**Issue by YZahringer** [bitstadium/HockeySDK-Xamarin#87]
Currently support for macOS by Xamarin is in beta with version 2.3.5. Would it be possible to provide a pre-release with macOS support?

**Comment by TroubleMakerBen** [comment]
Hey Yann,

we don't have any plans to add macOS support to the HockeySDK any time soon, although it's on our backlog at the very end.
But, for [Mobile Center](https://www.hockeyapp.net/mobile-center/about/), we are working on the native macOS SDK right now, and we will definitely have macOS support in the Mobile Center SDK for Xamarin. Unfortunately, I can't provide an ETA for it.

Thx for bringing this up, and stay tuned. We're working very hard on making Mobile Center awesome and make the transitioning experience for HockeyApp customers as smooth as possible.

Benny

**Comment by YZahringer** [comment]
Hello,

Ok thank you. I'm waiting for all hockeyapp features (UDID of devices per user, Windows Phone support, Mac OS support, distribution groups, ...) to be available on Mobile Center to migrate.
