### ISSUE TITLE
Error when updating to 4.1.5

### ISSUE THREAD

**Issue by JaCraig** [bitstadium/HockeySDK-Xamarin#90]
I updated a set of packages today and found that I'm now getting the following error:

System.TypeInitializationException: The type initializer for 'Attribute' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'HockeyApp.Resource/String.hockeyapp_feedback_attachment_added' not found.

Only happens on the Android side of things. Does not happen on the iOS app.

**Comment by TroubleMakerBen** [comment]
Hi @JaCraig,

Apologies for the slow response from our side.
We're looking into the issue and I'll let you know as soon as we're reproduced it.

Thank you for using HockeyApp!
Benny

**Comment by MatkovIvan** [comment]
Hi @JaCraig,

In this Android SDK version, we've added some localized strings including `hockeyapp_feedback_attachment_added`. All Android resources collect in generated (by Xamarin)  `Resources/Resource.Designer.cs` file. Looks like you need just regenerate this.
If you had a problem with regenerating this, please read [the article from Xamarin FAQ](https://developer.xamarin.com/guides/android/troubleshooting/questions/resource-designer-wont-update/).

**Comment by TroubleMakerBen** [comment]
I'm closing this as we haven't heard anything in the last week. Feel free to re-open if the issue persists.

**Comment by JaCraig** [comment]
Sorry, was off last week and didn't see @MatkovIvan's response. The resource file is being generated. No issues there. Tried removing the library, I see the items removed, add it back and they're there. Including one for hockeyapp_feedback_attachment_added. However as soon as we run the app, we get the crash and error message.

**Comment by MatkovIvan** [comment]
I cannot reproduce this behavior.
Did you build on Windows or Mac?
Could you please provide reproduction steps or some sample project?

PS: There is the same issue #89

**Comment by JaCraig** [comment]
Windows system. With the item you linked to we figured out that our server wasn't properly clearing everything. Went in, manually cleared everything, and we're back to working. You can close it again. :)
