### ISSUE TITLE
Are there plans to compile with .netstandard enabled?

### ISSUE THREAD

**Issue by bpater-tp** [bitstadium/HockeySDK-Xamarin#92]
Right now I VS refuses to install your nuget in my .netstandard library.

**Comment by MatkovIvan** [comment]
Hi. You may use this library with adding `imports` section into your `project.json` file.
It should look something like that:
```json
"frameworks": {
    "netstandard1.4": {
      "imports": "portable-win+net45+wp8+win81+wpa8"
    }
  }
```
If you are using new `.csproj` format instead `project.json` you may use `PackageTargetFallback` tag.
Also please note that this library is the only wrapper for Android and iOS ones and will not work on other platforms.

**Comment by abelgs1987** [comment]
Hi
I'm also in need a version of hockeyapp compatible with netstandard 1.4

Thanks

**Comment by Cheesebaron** [comment]
@abelgs1987 Just add PackageTargetFallback

**Comment by TroubleMakerBen** [comment]
Hey @abelgs1987 did @Cheesebaron 's hint solve this for you?

**Comment by abelgs1987** [comment]
I used 
"frameworks": {
    "netstandard1.4": {
      "imports": "portable-win+net45+wp8+win81+wpa8"
    }
  }

as commented by MatkovIvan. Although i don't think it is the best solution. it should target netstandard   without any fallback

**Comment by TroubleMakerBen** [comment]
Hi folks,

As we're working hard on [App Center](https://appcenter.ms), we won't fix this, so you need the workaround as described by @MatkovIvan .

I'm leaving this issue open for better visibility.

Thx for understanding!
Benjamin

**Comment by dupovalo** [comment]
[PackageTargetFallback] can't be used for _netcoreapp2.0_ and _netstandard2.0_ projects as it conflicts with [AssetTargetFallback] which is added automatically for those kinds of project (https://stackoverflow.com/a/45569379).

Attempt to using PackageTargetFallback will end up with a build error:
```
PackageTargetFallback and AssetTargetFallback cannot be used together. Remove PackageTargetFallback(deprecated) references from the project environment.
```

Without specifying the [PackageTargetFallback] or [AssetTargetFallback] tags explicitly, we get a warning:
```
Package 'HockeySDK.Xamarin 5.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

With the [AssetTargetFallback] tag specified explicitly in .csproj
```
<AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wpa81+wp8</AssetTargetFallback>
```
we get another warning:
```
Package 'HockeySDK.Xamarin 5.1.2' was restored using '.NETPortable,Version=v0.0,Profile=Profile259, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

**[?]** Is it ok to do not specify AssetTargetFallback and go with the default behavior? If no, which PCL profile is the best one to use with HockeyApp?

**Comment by jwallra** [comment]
It should be OK to use the default behavior, but you should check the functionality on any older devices you want to support (win8, wpa81, and wp8).  PCLs are only useful to support these older devices.  You can see a list of PCLs at this page: http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html

**Comment by ivmirx** [comment]
For anyone looking how to suppress the warning, open the project's `*.csproj` file with a text editor and add `NoWarn="NU1701"` attribute to the HockeySDK.Xamarin package.

For example: `<PackageReference Include="HockeySDK.Xamarin" Version="5.1.2" NoWarn="NU1701" />`

**Comment by pmahend1** [comment]
When will it ported to .Net standard?
