### ISSUE TITLE
Error opening iOS storyboards that goes away after removing Hockey 

### ISSUE THREAD

**Issue by jneno** [bitstadium/HockeySDK-Xamarin#99]
I'm opening this issue because of the _correlation_ described below, but this may not be a Hockey issue.

It isn't clear what the root cause of the issue is, and **it may well be Xamarin instead of Hockey**, but using the latest tooling (Xamarin Studio, Visual Studio for Mac, or Visual Studio for Windows), along with latest Xamarin releases causes an **error when creating new storyboards** or opening existing ones in a project that references the Hockey SDK. 

This was tested with the Hockey SDK version 5 (the latest) and 4.1.0-beta3.

When opening the storyboard a spinner is displayed for a bit and then a dialog is presented that reads:

**MonoTouchDesignServerUnified quit unexpectedly.**

After dismissing the dialog the storyboard appears with a yellow box at the top of the designer that reads:

**Custom components are not being rendered because problems were detected**

After removing the Hockey SDK from the project, the error no longer occurs, and after re-adding Hockey the error continues.

That said, other than the error, there are no obvious side-effects or errors that prevent one from managing and using storyboards.

Below is the detail on the tooling and versions in use:

=== Visual Studio Community 2017 for Mac ===

Version 7.2.2 (build 7)
Installation UUID: bea7a7b7-8ccc-457f-91d8-d618d3aed6e1
Runtime:
	Mono 5.4.1.6 (2017-06/1f4613aa1ac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010006

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/1.0.3/Sdks
SDK Version: 1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.6
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.0 (13247)
Build 9A235

=== Xamarin.Android ===

Version: 8.0.2.1 (Visual Studio Community)
Android SDK: /Users/james.neno/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.0   (API level 24)
		8.0   (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26
SDK Build Tools Version: 23.0.1

Java SDK: /usr
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.2.0.11 (Visual Studio Community)
Hash: 2f8bbec0
Branch: d15-4-xi
Build date: 2017-10-05 20:56:05-0400

=== Xamarin.Mac ===

Version: 3.8.1.0 (Visual Studio Community)

=== Build Information ===

Release ID: 702020007
Git revision: 2236098c68f51eeb447cb947a87371d1e84f6213
Build date: 2017-10-23 11:43:05-04
Xamarin addins: eaa605cf97f25ce184949f32c712b465ca96f665
Build lane: monodevelop-lion-d15-4

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by TroubleMakerBen** [comment]
Hey @jneno,

thanks for getting in touch and for providing all info about your setup. This is the first time I've heard anything like this, which I found quite intriguing (but it's side-effects are not cool). ;)
First:
HockeyApp doesn't do anything with storyboards or to Visual Studion, so it's quite weird.

I've tried to reproduce this with a sample project but I don't run into any issues at all, I can edit or add storyboards just fine – although it seems to be very slow here.
My best guess is that it's something with the lastes VS Studio for Mac.

[Here](https://www.dropbox.com/s/qqsf0aosud7lqv8/TestingStoryboardIssues.zip?dl=0) is my sample project, maybe you can give it a try? Let me know how this goes.



Best,
Benjamin

FYI this is my setup here (other than Xcode 9.1, I don't see any difference)

```=== Visual Studio Community 2017 for Mac ===

Version 7.2.2 (build 7)
Installation UUID: c4a2b986-096d-4c09-b80e-42de675683df
Runtime:
	Mono 5.4.1.6 (2017-06/1f4613aa1ac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010006

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/1.0.3/Sdks
SDK Version: 1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.6
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.1 (13532)
Build 9B55

=== Xamarin.iOS ===

Version: 11.2.0.11 (Visual Studio Community)
Hash: 2f8bbec0
Branch: d15-4-xi
Build date: 2017-10-05 20:56:05-0400

=== Xamarin.Android ===

Version: 8.0.2.1 (Visual Studio Community)
Android SDK: /Users/benny/Library/Android/sdk
	Supported Android versions:
		4.0.3 (API level 15)
		6.0   (API level 23)
		7.1   (API level 25)
		8.0   (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.1
SDK Build Tools Version: 27.0.0

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 3.8.1.0 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 702020007
Git revision: 2236098c68f51eeb447cb947a87371d1e84f6213
Build date: 2017-10-23 11:43:05-04
Xamarin addins: eaa605cf97f25ce184949f32c712b465ca96f665
Build lane: monodevelop-lion-d15-4

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Wed Oct  4 00:17:00 PDT 2017
    root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

```

**Comment by jneno** [comment]
I had unfortunately updated to the latest XCode before viewing this today, so I'm not comparing apples to apples (no punnage intended), but the project I was having trouble with yesterday now only exhibits the error when I'm targeting "Generic Device" as the debug target in the IDE, and it removing or adding Hockey has no effect. There is no error when I target the simulator, with or without Hockey.

The project that you provided does not trigger the error at all.

I believe there is no issue with Hockey at this point, and I'm not certain what the correlation was that I saw yesterday. 

I'd suggest this issue be closed.

**Comment by TroubleMakerBen** [comment]
Okay.

Good luck with the issue that you are seeing. =)
